In [63]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import StandardScaler

In [64]:
df = pd.read_csv('Iris.csv')
df.head(3)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [66]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [67]:
# extract the x and y
x = df.drop(columns=['Species'])
y = df['Species']

In [68]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [69]:
from sklearn.compose import ColumnTransformer

trf1 = ColumnTransformer(
    [
        ('standard', StandardScaler(), slice(0,4))
    ]
)

In [70]:
from sklearn.tree import DecisionTreeClassifier
trf2 = DecisionTreeClassifier()

In [71]:
pip = Pipeline(
    [
        ('trf1', trf1),
        ('trf2', trf2)
    ]
)

In [72]:
from sklearn.metrics import accuracy_score

pip.fit(x_train,y_train)
pred = pip.predict(x_test)
accuracy_score(y_test, pred)

1.0

In [73]:
from sklearn.decomposition import PCA

In [74]:
trf3 = PCA(n_components=2)

pipe2 = Pipeline([
    ('trf1', trf1),
    ('trf3', trf3),
    ('trf2', trf2)
])


In [75]:
pipe2.fit(x_train,y_train)
pred = pipe2.predict(x_test)
print(accuracy_score(y_test, pred))

pipe2.named_steps

1.0


{'trf1': ColumnTransformer(transformers=[('standard', StandardScaler(),
                                  slice(0, 4, None))]),
 'trf3': PCA(n_components=2),
 'trf2': DecisionTreeClassifier()}

In [76]:
from sklearn import set_config
set_config(display='diagram')

In [77]:
print(trf3.components_)

[[ 0.55370393  0.5108737  -0.2960881   0.58715574]
 [-0.01956688  0.44927208  0.88991485  0.07631054]]


In [78]:
trf3.explained_variance_

array([2.81635968, 0.93173122])

In [79]:
trf3.explained_variance_ratio_

array([0.6982225, 0.2309917])